service: wb-backend-python
 
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  environment:
    PYTHONPATH: /var/task

plugins:
  - serverless-wsgi
  - serverless-python-requirements
 
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: src.main.app
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true
    slim: true
    noDeploy:
      - pip
      - autopep8
      - debugpy
    compatibleRuntimes:
      - python3.8